# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-10 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow_feed', '0002_auto_20160910_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='tags',
            field=models.CharField(choices=[('garbage', 'garbage'), ('accident', 'accident')], default='asdf', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posts',
            name='up_vote',
            field=models.ManyToManyField(blank=True, to='flow_feed.Votes'),
        ),
    ]
